version: "3"
services:
  wolweb:
    container_name: wolweb
    image: ghcr.io/sameerdhoot/wolweb:latest
    restart: always
    ports:
      - 8089:8089
    network_mode: host
    environment:
      WOLWEBHOST: "0.0.0.0"
      WOLWEBPORT: "8089"
      #WOLWEBDIR: "/wolweb"
      WOLWEBBCASTIP: ${WOLWEBCASTIP}
    env_file: stack.env
